version: "3.8"

services:
  java-sandbox:
    build: ./java-sandbox
    image: java-sandbox:latest
    entrypoint: ["true"]

  code-executor:
    build: ./node-server
    image: code-executor:latest
    container_name: code-executor
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - java-sandbox
